// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/vue3/src/components/tiles/Grid.vue
<template>
    <Tile title="Grid">
        <wj-flex-grid
                :isReadOnly="true"
                :headersVisibility="'Column'"
                :selectionMode="'ListBox'"
                :itemsSource="data"
        >
            <wj-flex-grid-column :binding="'id'" :header="'ID'" :width="40"></wj-flex-grid-column>
            <wj-flex-grid-column :binding="'date'" :header="'Date'" :width="'*'" :format="'MMM yyyy'"></wj-flex-grid-column>
            <wj-flex-grid-column :binding="'sales'" :header="'Sales'" :format="'c'"></wj-flex-grid-column>
            <wj-flex-grid-column :binding="'expenses'" :header="'Expenses'" :format="'c'"></wj-flex-grid-column>
            <wj-flex-grid-column :binding="'profit'" :header="'Profit'" :format="'c'"></wj-flex-grid-column>
        </wj-flex-grid>
    </Tile>
</template>

<script>
    import Tile from './Tile.vue';
    import { WjFlexGrid, WjFlexGridColumn } from '@grapecity/wijmo.vue2.grid';
    import DataService from '../../services/data.service';

    export default {
        data: () => ({ data: DataService.getData() }),
        components: {
            Tile,
            WjFlexGrid,
            WjFlexGridColumn,
        },
    }
</script>

<style scoped>
</style>

// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/react/src/components/Grid.jsx
// React
import * as React from 'react';
// Wijmo
import * as wjcGrid from '@grapecity/wijmo.grid';
import * as wjGrid from '@grapecity/wijmo.react.grid';
export const Grid = ({ data, palette }) => (<wjGrid.FlexGrid isReadOnly={true} headersVisibility={wjcGrid.HeadersVisibility.Column} selectionMode={wjcGrid.SelectionMode.ListBox} itemsSource={data}>
		<wjGrid.FlexGridColumn header="ID" binding="id" width={50}/>
		<wjGrid.FlexGridColumn header="Date" width="*" binding="date" format="MMM yyyy"/>
		<wjGrid.FlexGridColumn header="Sales" binding="sales" format="c"/>
		<wjGrid.FlexGridColumn header="Expenses" binding="expenses" format="c"/>
		<wjGrid.FlexGridColumn header="Profit" binding="profit" format="c"/>
	</wjGrid.FlexGrid>);
