// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/vue/src/components/GdashSlider.vue
<template>
<div style="height: 34px">
  <div style="width:230px; height:1px; background:gray; position:relative;	top:50%">
    <div style="text-align:center; border-radius:5px; width:10px; height:10px; background:#d2d1cf; position:relative; left:50%; top:-5px;"></div>
    <div class="marker" :style="{background: palette[1], left: position}" style="text-align:center; border-radius:30px; width:30px; height:30px; line-height:30px; background:black; color:white; position:relative; top:-25px; left:25%">
        {{ value }}
    </div>
  </div>
</div>
</template>

<script>
export default {
  name: 'GdashSlider',
  props: {
    palette: Array,
    value: Number,
  },
  computed: {
    position: function() {
      // calculate slider position (as a percentage)
      let position = Math.log(this.value / 100);
      position = Math.min(Math.max(position, -1.5), +1.5);
      position = (position + 1.5) / 3;

      // convert to pixels
      position = position * 230 - 15;

      // apply position
      return position + 'px';
    }
  }
}
</script>

// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/react/src/components/GdashSlider.jsx
// React
import * as React from 'react';
export class GdashSlider extends React.Component {
    constructor() {
        super(...arguments);
        this.data = {
            position: 0,
            value: 0
        };
    }
    render() {
        this.updateData();
        const markerStyle = {
            background: this.props.color,
            textAlign: 'center',
            borderRadius: 25,
            width: 25,
            height: 25,
            lineHeight: '25px',
            position: 'relative',
            top: -23,
            fontSize: '0.75rem',
            left: this.data.position
        };
        return (<div style={{ height: 26 }}>
        <div style={{ width: '100%', height: 1, backgroundColor: '#d8dfe1', position: 'relative', top: '50%' }}>
          <div style={{ textAlign: 'center', borderRadius: 5, width: 10, height: 10, backgroundColor: '#d2d1cf', position: 'relative', left: '50%', top: -5 }}></div>
          <div className="marker" style={markerStyle}>
            {this.props.value}
          </div>
        </div>
      </div>);
    }
    updateData() {
        const value = this.props.value;
        if (value !== this.data.value) {
            this.data.position = this.calculatePosition(value);
            this.data.value = value;
        }
    }
    calculatePosition(value) {
        // calculate slider position (as a percentage)
        let position = Math.log(value / 100);
        position = Math.min(Math.max(position, -1.5), +1.5);
        position = (position + 1.5) / 3;
        // convert to pixels
        return position * 230 - 15;
    }
}
