// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/react/src/components/BarChart.jsx
// React
import * as React from 'react';
// Wijmo
import * as wjcChart from '@grapecity/wijmo.chart';
import * as wjChart from '@grapecity/wijmo.react.chart';
export const BarChart = ({ data, palette }) => (<wjChart.FlexChart chartType={wjcChart.ChartType.Bar} itemsSource={data} palette={palette} bindingX="date">
		<wjChart.FlexChartAxis wjProperty="axisX" format="MMM-yy"/>
		<wjChart.FlexChartSeries name="Sales" binding="sales"/>
		<wjChart.FlexChartSeries name="Expenses" binding="expenses"/>
		<wjChart.FlexChartSeries name="Profit" binding="profit" chartType={wjcChart.ChartType.LineSymbols}/>
	</wjChart.FlexChart>);

// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/vue3/src/components/tiles/BarChart.vue
<template>
    <Tile title="Bar Chart" v-slot="{palette}">
        <wj-flex-chart :chartType="'Bar'" :itemsSource="data" :bindingX="'date'" :palette="palette">
            <wj-flex-chart-axis :wjProperty="'axisX'" :format="'MMM yy'"></wj-flex-chart-axis>
            <wj-flex-chart-series :name="'Sales'" :binding="'sales'"></wj-flex-chart-series>
            <wj-flex-chart-series :name="'Expenses'" :binding="'expenses'"></wj-flex-chart-series>
            <wj-flex-chart-series :name="'Profit'" :binding="'profit'" :chartType="'LineSymbols'"></wj-flex-chart-series>
        </wj-flex-chart>
    </Tile>
</template>

<script>
    import Tile from './Tile.vue';
    import { WjFlexChart, WjFlexChartAxis, WjFlexChartSeries } from '@grapecity/wijmo.vue2.chart';
    import DataService from '../../services/data.service';

    export default {
        setup: () => ({ data: DataService.getData() }),
        components: {
            Tile,
            WjFlexChart,
            WjFlexChartAxis,
            WjFlexChartSeries,
        },
    }
</script>

<style scoped>
</style>
