// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/react/src/components/LinearGauge.jsx
// React
import * as React from 'react';
// Wijmo
import * as wjcCore from '@grapecity/wijmo';
import * as wjGauge from '@grapecity/wijmo.react.gauge';
export const LinearGauge = ({ data, palette }) => {
    const lastItem = data.items[data.items.length - 1];
    return (<div style={{ width: '100%' }}>
			<div className="flex-row">
				<h4>Sales: {wjcCore.Globalize.format(lastItem.sales, 'c')}</h4>
				<wjGauge.LinearGauge min={0} max={1000} thickness={0.15} thumbSize={9} value={lastItem.sales} pointer={{ color: palette[0] }}/>
			</div>

			<div className="flex-row">
				<h4>Expenses: {wjcCore.Globalize.format(lastItem.expenses, 'c')}</h4>
				<wjGauge.LinearGauge min={0} max={1000} thickness={0.15} thumbSize={9} value={lastItem.expenses} pointer={{ color: palette[1] }}/>
			</div>

			<div className="flex-row">
				<h4>Profit: {wjcCore.Globalize.format(lastItem.profit, 'c')}</h4>
				<wjGauge.LinearGauge min={0} max={1000} thickness={0.15} thumbSize={9} value={lastItem.profit} pointer={{ color: palette[2] }}/>
			</div>
			
			<h3>KPIs for {wjcCore.Globalize.format(lastItem.date, 'MMMM yyyy')}</h3>
		</div>);
};

// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/vue3/src/components/tiles/LinearGauge.vue
<template>
    <Tile title="Linear Gauge" v-slot="{palette}">
        <div class="line-gauge-tile">
            <div class="flex-row">
                <h4>Sales: {{ wjFormat(data.items[data.items.length - 1].sales, 'c') }}</h4>
                <wj-linear-gauge
                        :value="data.items[data.items.length-1].sales"
                        :min="0"
                        :max="1500"
                        :thickness="0.15"
                        :thumbSize="9"
                >
                    <wj-range :wjProperty="'pointer'" :color="palette[0]"></wj-range>
                </wj-linear-gauge>
            </div>

            <div class="flex-row">
                <h4>Expenses: {{ wjFormat(data.items[data.items.length - 1].expenses, 'c') }}</h4>
                <wj-linear-gauge
                        :value="data.items[data.items.length-1].expenses"
                        :min="0"
                        :max="1500"
                        :thickness="0.15"
                        :thumbSize="9"
                        :pointer="{ color: palette[1] }"
                >
                    <wj-range :wjProperty="'pointer'" :color="palette[1]"></wj-range>
                </wj-linear-gauge>
            </div>

            <div class="flex-row">
                <h4>Profit: {{ wjFormat(data.items[data.items.length - 1].profit, 'c') }}</h4>
                <wj-linear-gauge
                        :value="data.items[data.items.length-1].expenses"
                        :min="0"
                        :max="1500"
                        :thickness="0.15"
                        :thumbSize="9"
                        :pointer="{ color: palette[2] }"
                >
                    <wj-range :wjProperty="'pointer'" :color="palette[2]"></wj-range>
                </wj-linear-gauge>
            </div>

            <h3>KPIs for {{ wjFormat(data.items[data.items.length - 1].date, 'MMMM yyyy') }}</h3>
        </div>
    </Tile>
</template>

<script>
    import Tile from './Tile.vue';
    import { wjFormat } from '@grapecity/wijmo.vue2.core';
    import { WjLinearGauge, WjRange } from '@grapecity/wijmo.vue2.gauge';
    import DataService from '../../services/data.service';

    export default {
        setup: () => ({
            data: DataService.getData(),
            wjFormat,
        }),
        components: {
            Tile,
            WjLinearGauge,
            WjRange,
        },
    }
</script>

<style scoped>
</style>
