// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/react/src/components/RadialGauge.jsx
// React
import * as React from 'react';
// Wijmo
import * as wjcCore from '@grapecity/wijmo';
import * as wjGauge from '@grapecity/wijmo.react.gauge';
export const RadialGauge = ({ data, palette }) => {
    const lastItem = data.items[data.items.length - 1];
    return (<React.Fragment>
			<wjGauge.RadialGauge min={0} max={1000} format="c0" value={lastItem.profit}/>
			<h3>Profit for {wjcCore.Globalize.format(lastItem.date, 'MMMM yyyy')}</h3>
		</React.Fragment>);
};

// src/main/webapp/wijmo/reference-samples/samples/DynamicDashboard/vue3/src/components/tiles/RadialGauge.vue
<template>
    <Tile title="Radial Gauge">
        <wj-radial-gauge :value="data.items[data.items.length-1].profit" :min="0" :max="1000" :format="'c0'">
            <wj-range :wjProperty="'pointer'"></wj-range>
        </wj-radial-gauge>
        <h3>Profit for {{ wjFormat(data.items[data.items.length - 1].date, 'MMMM yyyy') }}</h3>
    </Tile>
</template>

<script>
    import Tile from './Tile.vue';
    import { wjFormat } from '@grapecity/wijmo.vue2.core';
    import { WjRadialGauge, WjRange } from '@grapecity/wijmo.vue2.gauge';
    import DataService from '../../services/data.service';

    export default {
        setup: () => ({
            data: DataService.getData(),
            wjFormat,
        }),
        components: {
            Tile,
            WjRadialGauge,
            WjRange,
        },
    }
</script>

<style scoped>
</style>
