// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/angular/src/app/components/gdash-tile.component.ts
﻿import { Component, Input, Output, EventEmitter } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'app-gdash-tile',
  templateUrl: './gdash-tile.component.html',
})
export class GdashTileComponent {
  @Input() header: string;
  @Input() icon: any;
  @Output() tileClick = new EventEmitter<any>();

  constructor(private sanitizer: DomSanitizer) {}

  get path() {
    return this.sanitizer.bypassSecurityTrustHtml(this.icon);
  }

  handleClick() {
    this.tileClick.emit();
  }
}

﻿<div class="tile" (click)="handleClick()">
  <div class="tile-header">
    <svg width="24" height="24" viewBox="0 0 24 24" [innerHtml]="path"></svg>
    <span>{{ header }}</span>
  </div>
  <div class="tile-content"><ng-content></ng-content></div>
</div>

// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/vue/src/components/GdashTile.vue
<template>
  <div class="tile" @click="$emit('tileClick')">
    <div class="tile-header">
      <svg width="24" height="24" viewBox="0 0 24 24" v-html="icon" />
      <span>{{header}}</span>
    </div>
    <div class="tile-content">
      <slot></slot>
    </div>
  </div>
</template>

<script>
export default {
  name: 'GdashTile',
  props: {
    header: String,
    icon: String,
  }
}
</script>
