// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/angular/src/app/components/gdash-slider.component.ts
﻿import { Component, Input, OnChanges, ViewChild } from '@angular/core';

@Component({
    selector: 'app-gdash-slider',
    templateUrl: './gdash-slider.component.html'
})
export class GdashSliderComponent implements OnChanges {
    position: string;

    @Input() value: number;
    @Input() color: string;
    @Input() palette: string[];

    constructor() {
    }

    ngOnChanges(changes: any) {
        if (!changes.value) {
            return;
        }
        let value = changes.value.currentValue;
        // calculate slider position (as a percentage)
        value = Math.log(this.value / 100);
        value = Math.min(Math.max(value, -1.5), +1.5);
        value = (value + 1.5) / 3;

        // convert to pixels
        value = value * 230 - 15;

        // apply position
        this.position = value + 'px';
    }
}

﻿<div style="height: 34px">
 <div style="width:230px; height:1px; background:gray; position:relative;	top:50%">
        <div style="text-align:center; border-radius:5px; width:10px; height:10px; background:#d2d1cf; position:relative; left:50%; top:-5px;"></div>
        <div class="marker" [ngStyle]="{background: palette[1], left: position}" style="text-align:center; border-radius:30px; width:30px; height:30px; line-height:30px; background:black; color:white; position:relative; top:-25px; left:25%">
            {{value}}
        </div>
    </div>
</div>

// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/vue/src/components/GdashSlider.vue
<template>
<div style="height: 34px">
  <div style="width:230px; height:1px; background:gray; position:relative;	top:50%">
    <div style="text-align:center; border-radius:5px; width:10px; height:10px; background:#d2d1cf; position:relative; left:50%; top:-5px;"></div>
    <div class="marker" :style="{background: palette[1], left: position}" style="text-align:center; border-radius:30px; width:30px; height:30px; line-height:30px; background:black; color:white; position:relative; top:-25px; left:25%">
        {{ value }}
    </div>
  </div>
</div>
</template>

<script>
export default {
  name: 'GdashSlider',
  props: {
    palette: Array,
    value: Number,
  },
  computed: {
    position: function() {
      // calculate slider position (as a percentage)
      let position = Math.log(this.value / 100);
      position = Math.min(Math.max(position, -1.5), +1.5);
      position = (position + 1.5) / 3;

      // convert to pixels
      position = position * 230 - 15;

      // apply position
      return position + 'px';
    }
  }
}
</script>
