// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/vue/src/components/EsriCrosshair.vue
<template>
  <div>
    <div :style="{ backgroundColor: palette[0], left: '50%', top: '50%', width: '8px', height: '8px', marginLeft: '-4px', marginTop: '-4px', borderRadius: '20px', zIndex: 2, }" class="crosshair crosshair-circle-xs" />
    <div :style="{ backgroundColor: color, left: '50%', top: '50%', width: '40px', height: '40px', marginLeft: '-20px', marginTop: '-20px', borderRadius: '20px', boxShadow: '0 1px 5px 0 rgba(0, 0, 0, 0.1)', zIndex: 1 }" class="crosshair crosshair-circle-sm" />
    <div :style="{ border: `20px solid ${palette[0]}`, left: '50%', top: '50%', width: '40px', height: '40px', marginLeft: '-40px', marginTop: '-40px', borderRadius: '100px', boxSizing: 'content-box', opacity: '0.25', zIndex: 0 }" class="crosshair crosshair-circle-lg" />
  </div>
</template>

<script>
export default {
  name: 'EsriCrosshair',
  props: {
    color: String,
    palette: Array
  }
}
</script>

// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/angular/src/app/components/esri-crosshair.component.ts
﻿import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-esri-crosshair',
    templateUrl: './esri-crosshair.component.html'
})
export class EsriCrosshairComponent {
    @Input() palette: string[];
    @Input() color: string;

    constructor() {
    }
}

﻿<div>
  <div
    [ngStyle]="{ borderColor: palette[0] }"
    style="
      position: absolute;
      border: 20px solid transparent;
      left: 50%;
      top: 50%;
      width: 40px;
      height: 40px;
      margin-left: -40px;
      margin-top: -40px;
      border-radius: 100px;
      box-sizing: content-box;
      opacity: 0.25;
      z-index: 0;
    "
    class="crosshair crosshair-circle-lg"
  ></div>
  <div
    style="
      position: absolute;
      left: 50%;
      top: 50%;
      width: 40px;
      height: 40px;
      margin-left: -20px;
      margin-top: -20px;
      border-radius: 20px;
      background-color: rgba(255, 255, 255, 0.7);
      box-shadow: 0 1px 5px 0 rgba(0, 0, 0, 0.1);
      z-index: 1;
    "
    class="crosshair crosshair-circle-sm"
  ></div>
  <div
    [ngStyle]="{ backgroundColor: palette[0] }"
    style="
      position: absolute;
      left: 50%;
      top: 50%;
      width: 8px;
      height: 8px;
      margin-left: -4px;
      margin-top: -4px;
      border-radius: 20px;
      z-index: 2;
    "
    class="crosshair crosshair-circle-xs"
  ></div>
</div>
