// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/vue/src/components/EsriLegend.vue
<template>
  <div class="legend-list" v-if="source" v-show="source">
    <div class="legend-item" v-for="(legend, index) in source.legends" :key="index">
      <div :style="{ margin: '0 .75rem 0 0', width: '1rem', height: '1rem', display: 'inline-block', 'background-color': legend.color }"></div>
      {{ legend.label }}
    </div>
 </div>
</template>

<script>
export default {
  name: 'EsriLegend',
  props: {
    source: Object
  }
}
</script>

// src/main/webapp/wijmo/reference-samples/samples/GeoDashboard/angular/src/app/components/esri-legend.component.ts
﻿import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-esri-legend',
    templateUrl: './esri-legend.component.html'
})
export class EsriLegendComponent {
    @Input() source: any;

    constructor() {
    }
}

﻿<div
  class="legend-list"
  [ngStyle]="{ display: source ? '' : 'none' }"
  *ngIf="source"
>
  <div class="legend-item" *ngFor="let legend of source.legends">
    <div
      [ngStyle]="{
        margin: '0 .75rem 0 0',
        width: '1rem',
        height: '1rem',
        display: 'inline-block',
        'background-color': legend.color
      }"
    ></div>
    {{ legend.label }}
  </div>
</div>
